apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: sark-prod

nameSuffix: -prod

commonLabels:
  environment: production

replicas:
  - name: sark-api
    count: 5

images:
  - name: sark
    newName: registry.example.com/sark
    newTag: v1.0.0

configMapGenerator:
  - name: sark-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - REPLICAS="5"

patchesStrategicMerge:
  - deployment-patch.yaml
