apiVersion: v1
kind: ServiceAccount
metadata:
  name: sark-frontend
  namespace: sark
  labels:
    app.kubernetes.io/name: sark
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
