apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sark

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  # Frontend resources
  - frontend-serviceaccount.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-hpa.yaml
  - frontend-ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: sark
    newTag: latest
  - name: sark-frontend
    newTag: latest
